### ISSUE TITLE
block-ref shortcut key

### ISSUE THREAD

**Issue by hillsmao** [hkgnp/logseq-randomutils-plugin#1]
Hello, master, can you provide a shortcut key to turn on or off the block-ref when the block is focused?

**Comment by benjypng** [comment]
Sorry am not sure what you mean?

**Comment by hillsmao** [comment]
> Sorry am not sure what you mean?

<img width="738" alt="image" src="https://user-images.githubusercontent.com/107061250/233236767-72635d15-8c26-4a0c-a4d4-1a2b1411492f.png">

**Comment by benjypng** [comment]
Sorry, I am still not sure what you mean by turning off the block-ref?

**Comment by hillsmao** [comment]
> Sorry, I am still not sure what you mean by turning off the block-ref?

That is, I want a shortcut key to turn on or off block-ref

**Comment by benjypng** [comment]
Sorry mate, still don't quite understand your requirement. You may need to supply more screenshots to illustrate your point.

**Comment by hillsmao** [comment]
<img width="841" alt="image" src="https://user-images.githubusercontent.com/107061250/233683843-9dfb89bd-b6f8-4e45-bce2-bd0ebe7fcaa1.png">
<img width="869" alt="image" src="https://user-images.githubusercontent.com/107061250/233684317-330d74fc-ed95-46a4-8f26-794cc9e24689.png">
<img width="815" alt="image" src="https://user-images.githubusercontent.com/107061250/233684855-eae30fad-3c47-4242-8cda-fe057965a10b.png">
<img width="832" alt="image" src="https://user-images.githubusercontent.com/107061250/233684919-5a75c0cf-6858-4c7a-ac1f-4ff09cf4be09.png">

**Comment by benjypng** [comment]
Hmm, am not able to reproduce the above screenshot. Is it a custom query you have implemented?

**Comment by hillsmao** [comment]
look this

https://docs.logseq.com/#/page/the%20basics%20of%20block%20references

**Comment by benjypng** [comment]
I see. Sorry this is not possible as:
1) There is no plugin API to open and close block references
2) You can have many block references in the same page and the shortcut would not know which one to target.

**Comment by hillsmao** [comment]
Thanks for answering!
